### ISSUE TITLE
backslash in search-replace and search-replace output dependent 

### ISSUE THREAD

**Issue by dropsplash** [ute/search-replace#3]
Hello,

Thanks for yout code; very useful.
Would it be possible to have in 
---
search-replace:
  \quarto : "Quarto something"
"\quarto": "Quarto something"
"\\quarto":  "Quarto" 
---

It seems that the backslash in any form of the previous yaml header can not be used to trigger a search-replace; maybe I missed something  

Also, it would be nice to have the possibility of having a search replacement that is format output-dependent. The same keyword with different output depending on the format is pdf, HTML, Latex, or Word. Do you have any idea how to do that? 

Many thanks 
Regards

**Comment by ute** [comment]
Backslash is an escape character and gets processed or rather throws errors before the filter can do its work. You would need to use double backslash: "\\quarto" is working. It then also needs to be doubled in the text.
It seems you are trying to replace LaTeX macros (I was hoping to be able to do that, too). One way to go is using pandoc to translate LaTeX into markdown.

Your other suggestion, with format dependent replacements, sounds interesting. I think it could be done, but it will require a big rewrite, including defining some sensible yaml syntax, or making the filter read translation lists from files. I wish I had time for coding - it is not going to happen in the next six months or so. If you (or someone else) wants to tackle this enhancement, a pull request would be very welcome :-)

**Comment by dropsplash** [comment]
Hello, 

I can't make it work \quarto either with one or two backslash

> Your other suggestion, with format dependent replacements, sounds interesting. I think it could be done, but it will require a big rewrite, including defining some sensible yaml syntax, or making the filter read translation lists from files. I wish I had time for coding - it is not going to happen in the next six months or so. If you (or someone else) wants to tackle this enhancement, a pull request would be very welcome :-)

For my other suggestion, I found in the doc [here](https://quarto.org/docs/extensions/formats.html#common-metadata) a way to have a format-dependent option. I did not try but it seems that it is already directly implemented in quarto.

contributes:
  format:
    common:
      filters:
        - filter.lua
      shortcodes:
        - quarto-ext/fancy-text
    html:
      # html-specifc
    pdf:
      # pdf-specifc

**Comment by ute** [comment]
Hmmm... It worked with double backslash for me. You need to put apostrophes around, and use double backslash also in the text. 

As for your yaml suggestion: if I understand you right, you suggest that parts of the yaml are read and processed depending on whether they appear under html or under other formats. That would be a cool feature of quarto. To my knowledge, it does not exist (yet?) 

An implementation for the search-replace extension would require that the filter checks a yaml-key against the current format. This can in principle be done with a bit of spare time.

**Comment by ute** [comment]
@dropsplash , thank you for your feature suggestion! Ive put this into a separate issue, https://github.com/ute/search-replace/issues/4.

Are you still having trouble with backslashes? If yes, which quarto version are you using?

**Comment by ute** [comment]
Format specific search replace is coming soon.
